# Generated by Django 3.2.5 on 2021-07-25 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('SD', 'Sindh'), ('KPK', 'Pakthunkhwa'), ('ISB', 'Islamabad')], max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], max_length=100, verbose_name='year')),
                ('condition', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('carphoto', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('carphoto1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('carphoto2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('carphoto3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('carphoto4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('features', models.CharField(choices=[('1', 'first_features'), ('2', 'second_features'), ('3', 'third_features'), ('4', 'fourth_features')], max_length=100)),
                ('body_style', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('interior', models.CharField(max_length=255)),
                ('doors', models.CharField(choices=[('8', '8'), ('2', '2'), ('4', '4'), ('6', '6')], max_length=100)),
                ('vin_no', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
