# Generated by Django 3.2.5 on 2021-08-01 09:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210801_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('4', '4'), ('2', '2'), ('3', '3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'first_features'), ('2', 'second_features'), ('3', 'third_features'), ('4', 'fourth_features')], max_length=7),
        ),
    ]
