# Generated by Django 3.2.5 on 2021-08-01 09:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210801_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('6', '6'), ('4', '4'), ('3', '3'), ('2', '2'), ('5', '5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('first_features', 'first_features'), ('second_features', 'second_features'), ('third_features', 'third_features'), ('fourth_features', 'fourth_features')], max_length=61),
        ),
    ]
